### ISSUE TITLE
how to scroll table `tbody`?

### ISSUE THREAD

**Issue by bayukartiko** [rizzui/rizzui#101]
I tried with class `max-h` `overflow-y` and more, but the scroll bar is still not visible. except using `block` which breaks the styles

**Comment by bayukartiko** [comment]
like this:
![image](https://github.com/user-attachments/assets/f154200d-9f7d-4315-84d2-237de9878eca)

**Comment by md-nahid** [comment]
Hi @bayukartiko 

It’s not possible to add a scroll directly inside the table body, but you can create a scrollable effect by placing the table inside an outer scroll container instead.

Here’s a helpful example to guide you through the setup:

**Example: Wrapping the Table in a Scrollable Container**

For the full example and customization options, check out the [RizzUI documentation on integrating with TanStack Table](https://www.rizzui.com/docs/integrations/tan-stack).
