### ISSUE TITLE
in pagination showQuickJumper doesn't work

### ISSUE THREAD

**Issue by abdarker** [rizzui/rizzui#107]

**Comment by md-nahid** [comment]
@abdarker Can you provide us anything how to generate the issue ?

**Comment by abue-ammar** [comment]
![image](https://github.com/user-attachments/assets/320664fc-10fa-43a4-b099-bd250a66f9db)
![image](https://github.com/user-attachments/assets/f9256095-c733-4d1d-8ea0-802e338af499)
![image](https://github.com/user-attachments/assets/b581e5a4-5d34-4d65-99a4-e527ee873ecf)

https://pagination-react-component.vercel.app/demo/show-size-changer
it should show 
![image](https://github.com/user-attachments/assets/6f1239bd-157f-485d-87c3-b29e4bbc8eee)
this. 

my findings:  you are missing this rc-selection as a prop to rc-pagination
![image](https://github.com/user-attachments/assets/256deea6-b1e8-453c-9d33-24467f9ed97c)

hoping you would implement it
