### ISSUE TITLE
Why bundle size is huge? 220 KB for just importing Input element

### ISSUE THREAD

**Issue by razb-viola** [rizzui/rizzui#59]
Bundle size is one of the most important thing. I installed the library and included the Input or Button components and from 82KB (blank Next.js project) it inflated to 220KB... 
The overall bundle should never exceed 100KB for first load, isn't it?

**Comment by razb-viola** [comment]
Also, Select auto intellisense with VSCode is extremely slow.

**Comment by razb-viola** [comment]
I saw the problem - it is because you export the whole package object instead of per module import, this is what you do:

`import { Button, Text, Title } from 'rizzui`

This is problematic since it imports all of the package, instead just button, text and title (80kb instead of less than 5kb).

Instead you should allow:

```
import { Button } from 'rizzui/Button'
import { Text } from 'rizzui/Text'
import { Title } from 'rizzui/Title'
```

Can it be fixed?

**Comment by bayukartiko** [comment]
+1

**Comment by jpainam** [comment]
Is there any update on this? The bundle size is huge

**Comment by neamatmim** [comment]
Hi @razb-viola thanks for addressing the issue. can you also give us some information like 
The environment you use, ex:

- Version Number (Package Version, NextJs Version, OS, etc)
- Steps to reproduce
- Any Additional Context

**Comment by razb-viola** [comment]
Next.js version 14.2.x
And actually not too much steps to reproduce.. Once you import a button you import all of the components. I guess this can be optimized, isn't it?

**Comment by idris95** [comment]
Hey @razb-viola! 

🚀 We've rolled out v1.0.0, and this issue has been addressed. Give it a try and let us know how it works for you! 🙌
