### ISSUE TITLE
components are not getting customizable specially when try to change boundary color when field is active

### ISSUE THREAD

**Issue by prithvi5481** [rizzui/rizzui#61]

**Comment by idris95** [comment]
Hi @prithvi5481, we're using the primary color for input hover and focus effects. If your design requires a change to the primary color, feel free to make adjustments accordingly.

However, if you only need to modify a specific input component without affecting the primary color, you can use the provided code ->

```javascript
<Input 
    inputClassName="[&.is-focus]:border-blue [&.is-focus]:ring-blue [&.is-hover]:border-blue [&.is-hover]:ring-blue" 
/>
```
