### ISSUE TITLE
c.findIndex is not a function

### ISSUE THREAD

**Issue by zhondori** [rizzui/rizzui#62]
I'm getting this error while using `<Select />` component and trying to allow multiple values.

![image](https://github.com/rizzui/rizzui/assets/83527629/4be27075-ed66-4178-932f-ddea3df0fb99)

**Comment by neamatmim** [comment]
Hi @zhondori could you please give us some info like

- Version Number
- Codesandbox Example
- Steps to reproduce
- Any Additional Context

**Comment by idris95** [comment]
Hi @zhondori!

This issue couldn't be reproduced, so it's being marked as closed. If you encounter it again with our latest version, please open a new ticket with the version number and steps to reproduce the issue. Thank you!
