### ISSUE TITLE
change default placeholder

### ISSUE THREAD

**Issue by bayukartiko** [rizzui/rizzui#64]
can you change this default placeholder from `Screen reader only` to [`&zwj;`](https://en.wikipedia.org/wiki/Zero-width_joiner)?
![image](https://github.com/rizzui/rizzui/assets/53922896/49478717-424c-49d1-b35e-1c66c5604288)

Version Number: 0.8.4

**Comment by idris95** [comment]
Hi, @bayukartiko! it will be fixed in our upcoming update. Thanks for reporting the issue.

**Comment by idris95** [comment]
@bayukartiko, the issue has been resolved in our RizzUI version 0.8.5.
