### ISSUE TITLE
Is there a way to customize the modal so that it doesnot closed when closed outside the modal body?

### ISSUE THREAD

**Issue by RajThapa7** [rizzui/rizzui#68]
I want the modal to only close when closed using the close button inside the modal body and not when clicked outside the modal body

**Comment by AlifSakib** [comment]
Yes , Try this 

  const handleClose = (e: React.MouseEvent) => {
    // Prevent closing on backdrop click
    if (e.target === e.currentTarget) {
      return;
    }
    onClose();
  };
  
  Pass the handle close function in Modal onClose function
  
  Hope it will work.

**Comment by RajThapa7** [comment]
@AlifSakib 
Thank you for answering but the onClose function in the Modal is of type
onClose(): void
so when I pass the handleClose function with the event handler I get type error

**Comment by md-nahid** [comment]
@RajThapa7 
You can just provide a blank callBack to the onClose like this
![image](https://github.com/user-attachments/assets/6f4ad8c0-d206-4774-a904-dca2c9cd5ce8)
