### ISSUE TITLE
Ran an npm update and getting this error

### ISSUE THREAD

**Issue by itskush** [rizzui/rizzui#72]
Failed to compile
./node_modules/rizzui/dist/index.mjs
Attempted import error: 'Label' is not exported from '__barrel_optimize__?names=Label,Listbox,ListboxButton,ListboxOption,ListboxOptions,Transition!=!@headlessui/react' (imported as 'li').

**Comment by itskush** [comment]
Also isomorphic is broken when running npm install cause of rizzui
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: isomorphic@7.0.0
npm ERR! Found: @headlessui/react@1.7.19
npm ERR! node_modules/@headlessui/react
npm ERR!   @headlessui/react@"^1.7.19" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @headlessui/react@">=2.0.3" from rizzui@0.8.5
npm ERR! node_modules/rizzui
npm ERR!   rizzui@"^0.8.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by idris95** [comment]
@itskush please upgrade your @headlessui/react & @floating-ui/react packages. 

`npm i @headlessui/react@2.0.3 @floating-ui/react@0.26.13`
