### ISSUE TITLE
Accordion issue

### ISSUE THREAD

**Issue by chualeesiong** [rizzui/rizzui#73]
Using the Accordion seems to cause issues with Typescript
Type error: Type '({ open }: {    open: boolean;}) => JSX.Element' is not assignable to type '((string | number | bigint | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal | Promise<...> | (({ open }: { ...; }) => ReactNode)) & (string | ... 6 more ... | Promise<...>)) | null | undefined'.
  Type '({ open }: {    open: boolean;}) => JSX.Element' is not assignable to type '(({ open }: { open: boolean; }) => ReactNode) & string'.
    Type '({ open }: {    open: boolean;}) => JSX.Element' is not assignable to type 'string'.

  27 |   <Accordion className="mx-8 border-b last-of-type:border-b-0">
  28 |     <Accordion.Header>
> 29 |       {({ open }: { open: boolean }) => (
     |        ^
  30 |         <div className="flex w-full cursor-pointer items-center justify-between py-5 text-xl font-semibold">
  31 |           Order Details
  32 |           <ChevronDownIcon
Thanks

**Comment by md-nahid** [comment]
Hi @chualeesiong 

We tried to generate the issue but couldn't. Could you please give us some info like

- Version Number
- CodeSandbox Example 
- Steps to reproduce
- Any Additional Context

Thanks
