### ISSUE TITLE
Select Dropdown Option is Not Showing In Modal When The Modal is Initiated from Popover

### ISSUE THREAD

**Issue by hariharan1309** [rizzui/rizzui#83]
Everything Except the Select Options is working fine when added absolute for the dropdownClassName with an index of [99999] The dropdown still shows the other functionality like the selection is not working..
My Modal Trigger  through PopOver Code 
         <Popover
          isOpen={openPopoverId === row.id}
          setIsOpen={(isOpen) => setOpenPopoverId(isOpen ? row.id : null)}
        >
          <Popover.Trigger>
            <ActionIcon
              onClick={() => setOpenPopoverId(openPopoverId === row.id ? null : row.id)}
              className="action-icon-wrapper"
              variant="text"
            >
              <MoreVertical size="20" />
            </ActionIcon>
          </Popover.Trigger>
          <Popover.Content>
          <div className="flex flex-col justify-start m-[2]">
              <EditModal
                member={row}
                onUpdate={(updatedMember) => {
                  console.log('Member updated:', updatedMember);
                  setOpenPopoverId(null); // Close popover after update
                }}
              />
              {
                row.due > 0 && <PaymentModal membershipid={row.membership_id} />
              }
                <Button
                  // size="sm"
                  variant="text"
                  // onClick={() => setIsOpen(true)}
                  className="flex flex-row gap-2 items-center justify-start font-medium hover:scale-105 duration-300"
                >
                  <RiLoopLeftLine size={20} />
                  <Text>Renew</Text>
                </Button>
              <DeleteModal memberId={row.member_id} />
            </div>
          </Popover.Content>
        </Popover>

const EditModal: React.FC<{ member: Member; onUpdate: (updatedMember: Member) => void }> = ({ member, onUpdate }) => {
// My Declarations 
  };
  return (
    <>
      <Button
        // size="sm"
        variant="text"
        onClick={() => setIsOpen(true)}
        className="flex flex-row gap-2 items-center justify-start font-medium hover:scale-105 duration-300"
      >
        <MdEdit size={18} />
        <Text>Edit</Text>
      </Button>
      <Modal isOpen={isOpen} onClose={() => setIsOpen(false)}>
        <div className="m-auto px-7 pt-6 pb-8">
          <div className="mb-7 flex items-center justify-between">
            <Text><h3>Edit Member</h3></Text>
            <ActionIcon
              size="sm"
              variant="text"
              onClick={() => setIsOpen(false)}
            >
              <X className="h-auto w-6" strokeWidth={1.8} />
            </ActionIcon>
          </div>
          <div className="grid grid-cols-2 gap-y-6 gap-x-5 [&_label>span]:font-medium">
              
            <Input
              name="name"
              label="Name *"
              placeholder="Enter Full Name"
              value={data.name}
              onChange={handleInputChange}
            />
            <Input
              name="email"
              label="Email *"
              placeholder="Enter email"
              value={data.email}
              onChange={handleInputChange}
            />
            <PhoneNumber
              label="Phone Number *"
              country="us"
              value={data.phone}
              onChange={handlePhoneChange}
            />
            <Input
              name="date_of_birth"
              type="date"
              label="Date of Birth"
              value={data.date_of_birth}
              onChange={handleInputChange}
            />
            <Input
              name="joining_date"
              type="date"
              label="Joining Date"
              value={data.joining_date}
              onChange={handleInputChange}
            />
            <Select
              name="gender"
              label="Gender"
              options={[
                { label: 'Male', value: 'male' },
                { label: 'Female', value: 'female' },
                { label: 'Other', value: 'other' }
              ]}
              value={data.gender}
              onChange={({value}:{label:string,value:string}) => setData((prev) => ({ ...prev, gender: value }))}
            />
            <Input
              name="address_street"
              label="Street Address"
              placeholder="Street Address"
              className="col-span-full"
              value={data.address_street}
              onChange={handleInputChange}
            />
            <Input
              name="address_state"
              label="State"
              placeholder="State"
              value={data.address_state}
              onChange={handleInputChange}
            />
            <Input
              name="address_city"
              label="City"
              placeholder="City"
              value={data.address_city}
              onChange={handleInputChange}
            />
            <Input
              name="address_country"
              label="Country"
              placeholder="Country"
              value={data.address_country}
              onChange={handleInputChange}
            />
            <Input
              name="address_zip_code"
              label="ZIP / Postcode"
              placeholder="ZIP / postcode"
              value={data.address_zip_code}
              onChange={handleInputChange}
            />
          </div>
          <div className="mt-6 flex justify-end gap-3">
            <Button variant="outline" onClick={() => setIsOpen(false)}>
              Cancel
            </Button>
            <Button variant="solid" color="primary" onClick={handleEdit}>
              Update
            </Button>
          </div>
        </div>
      </Modal>
    </>
  );
};

**Comment by md-nahid** [comment]
Hi @hariharan1309 

We can not regenerate the issue you are facing.

Can you provide a code-sandbox example or GitHub repo where we can see or regenerate the issue.
