### ISSUE TITLE
MultiSelect CheckBox is not working

### ISSUE THREAD

**Issue by syoo970** [rizzui/rizzui#85]
The checkbox component of a MultiSelect doesn't seem to be working and needs to be checked

https://github.com/user-attachments/assets/52c635f1-5c58-4d7a-b8c8-bcf426c17d61

**Comment by md-nahid** [comment]
Hi @syoo970 Thanks for addressing the issue.

Will update soon.

**Comment by md-nahid** [comment]
Hi @syoo970 

We’ve updated RizzUI with the feature you requested. Updating RizzUI should resolve the issue.

Thanks!
