### ISSUE TITLE
Cannot add `node_modules/rizzui/dist` to Tailwind

### ISSUE THREAD

**Issue by oalexdoda** [rizzui/rizzui#87]
Hi,

I'm new to Tailwind. Using Bun monorepo / Turborepo / Next.js with a bunch of apps and packages.

When I install all the deps in the app, they actually live in the node_modules folder of the monorepo, not of each app/package.

I assume it's something by design in Bun.sh or Turborepo.

Which means i can't just do `../../node_modules/rizzui/dist` in the content object for Tailwind.

Any other way to add the JS files? A plugin or some other way?

The only workaround I found was to move `rizzui` as a package under root/packages, but looking to just import it from the native module.

Thanks!

**Comment by md-nahid** [comment]
Hi @oalexdoda can you share your mono-repo as an example

Just so we can look into it how your are using tailwind with turbo-repo
