### ISSUE TITLE
Please use headlessui v2.1.x

### ISSUE THREAD

**Issue by bayukartiko** [rizzui/rizzui#94]
I need that headlessui v.2.1 or newer, because they have added a [multiple modal](https://tailwindcss.com/blog/2024-06-21-headless-ui-v2-1#rendering-multiple-dialogs-as-siblings) feature.

I also take a look into your product [Isomorphic - React Admin Dashboard Template v7.2.0](https://themeforest.net/item/isomorphic-react-redux-admin-dashboard/20262330) is still using headlessui v2.0. can you also upgrade that?

**Comment by idris95** [comment]
@bayukartiko, we’re planning to roll out the newer version in our next update! In the meantime, you can still get multiple modals working by nesting them inside each other.
