### ISSUE TITLE
Cannot use full-rounded or change width/height in Advaned radio/checkbox 

### ISSUE THREAD

**Issue by tauhid97k** [rizzui/rizzui#96]
Radio/Checkbox doesn't have full rounded option. Overriding with classes does not work. Also, width and height are set to a minimum of 40px and 90px. Without using !important inside contentClassName I cannot update it. There should've been a better way to override this easily by internally using the cn() function.  Or maybe I am missing something. I wanted the radio to be rounded for my product variant color options.

**Comment by md-nahid** [comment]
@tauhid97k Thank you for your efforts so far!

Please refrain from using **rounded=full** and instead use **pill** for fully rounded corners. Additionally, we have implemented minimum width and height requirements, so you don’t need to manually add these attributes. The **cn()** function is handled internally, and the **contentClassName** is working as expected without needing **!important**. Kindly ensure you're following our documentation closely. If you continue to face any issues, feel free to reach out for further assistance.
