### ISSUE TITLE
Make Search Input Sticky in Scrollable List of Select Options

### ISSUE THREAD

**Issue by bayukartiko** [rizzui/rizzui#98]
When scrolling through the list of options in the Select component with the search functionality, the search input field currently disappears. The expected behavior is for the search input to remain visible and fixed at the top of the dropdown while scrolling through the options.

current:
![image](https://github.com/user-attachments/assets/f77abec0-331a-415b-ae70-e31bb360f206)

expected:
![image](https://github.com/user-attachments/assets/b299f2fb-b8f4-4704-8528-bea0425d34df)

rizzui version: 0.8.7

**Comment by md-nahid** [comment]
#100 Added this feature in this PR
